spring:
  application:
    name: warchest

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/warchest}
    username: ${DATABASE_USER:warchest}
    password: ${DATABASE_PASSWORD:warchest}

  jpa:
    hibernate:
        ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${PORT:8080}

warchest:
  mlb-api:
    base-url: https://statsapi.mlb.com/api/v1
    sport-id: 1
  import:
    bat-file: data/war_daily_bat.txt

management:
  endpoints:
    web:
      exposure:
        include: health, info
